# Generated by Django 4.0.5 on 2022-06-07 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_flashcards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_lv1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_lv2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_lv3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_lv4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_lv5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='web.userprofile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
        migrations.CreateModel(
            name='FlashCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('definition', models.CharField(max_length=512)),
                ('synonyms', models.CharField(max_length=512)),
                ('example', models.CharField(default=None, max_length=1024)),
                ('lv', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
        ),
    ]
